LOW_RELEVANCE_THRESHOLD = 0.45
NEIGHBOR_JACCARD_THRESHOLD = 0.30
COMMON_NEIGHBOR_THRESHOLD = 6
LOCAL_DENSITY_THRESHOLD = 0.25
LOCAL_DENSITY_MIN_JACCARD = 0.10
MAX_SECTION_CHARS = 2500
MAX_BM25_QUERY_KEYWORDS = 80
